Update TriggerWaitBox.yml

diff --git a/.github/workflows/TriggerWaitBox.yml b/.github/workflows/TriggerWaitBox.yml
--- a/.github/workflows/TriggerWaitBox.yml
+++ b/.github/workflows/TriggerWaitBox.yml
@@ -29,8 +29,63 @@ jobs:
           event-type: start-workflow
           client-payload: '{"ref": "main"}'
 
+      # - name: Wait for trigger-edge-rt-build
+      #   id: wait-trigger-edge-rt-build
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
+      #   run: |
+      #     echo "Waiting for workflow '${{ env.WORKFLOW_NAME }}' in ${{ env.REPO_B }} to complete on ${{ env.OS_NAME }}..."
+          
+      #     START_TIME=$(date +%s)
+      #     TIMEOUT=300 # 5 minutes
+
+      #     while true; do
+      #       CURRENT_TIME=$(date +%s)
+      #       ELAPSED=$((CURRENT_TIME - START_TIME))
+
+      #       # Fetch the workflow run ID
+      #       RUN_ID=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+      #         "https://api.github.com/repos/${{ env.REPO_B }}/actions/workflows" \
+      #         | jq -r ".workflows[] | select(.name==\"${{ env.WORKFLOW_NAME }}\") | .id")
+
+      #       if [ -z "$RUN_ID" ]; then
+      #         echo "Workflow not found!"
+      #         exit 1
+      #       fi
+
+      #       # Fetch the status and conclusion of the latest run
+      #       RUN_INFO=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+      #         "https://api.github.com/repos/${{ env.REPO_B }}/actions/workflows/$RUN_ID/runs?branch=${{ env.BRANCH }}&per_page=1" \
+      #         | jq -r '.workflow_runs[0]')
+
+      #       RUN_STATUS=$(echo "$RUN_INFO" | jq -r '.status')
+      #       CONCLUSION=$(echo "$RUN_INFO" | jq -r '.conclusion')
+
+      #       echo "Current status: $RUN_STATUS"
+
+      #       if [ "$RUN_STATUS" == "completed" ]; then
+      #         echo "Workflow completed with conclusion: $CONCLUSION"
+      #         if [ "$CONCLUSION" == "success" ]; then
+      #           echo "::set-output name=result::success"
+      #           exit 0
+      #         else
+      #           echo "::set-output name=result::failure"
+      #           exit 1
+      #         fi
+      #       fi
+            
+      #       if [ "$ELAPSED" -ge "$TIMEOUT" ]; then
+      #         echo "Workflow stuck in '$RUN_STATUS' or failed for more than 5 minutes. Terminating..."
+      #         echo "::set-output name=result::failure"
+      #         exit 1
+      #       fi
+
+      #       sleep 15
+      #     done
+
       - name: Wait for trigger-edge-rt-build
         id: wait-trigger-edge-rt-build
+        shell: bash
         env:
           GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
         run: |
@@ -38,31 +93,31 @@ jobs:
           
           START_TIME=$(date +%s)
           TIMEOUT=300 # 5 minutes
-
+      
           while true; do
             CURRENT_TIME=$(date +%s)
             ELAPSED=$((CURRENT_TIME - START_TIME))
-
+      
             # Fetch the workflow run ID
             RUN_ID=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ env.REPO_B }}/actions/workflows" \
               | jq -r ".workflows[] | select(.name==\"${{ env.WORKFLOW_NAME }}\") | .id")
-
+      
             if [ -z "$RUN_ID" ]; then
               echo "Workflow not found!"
               exit 1
             fi
-
+      
             # Fetch the status and conclusion of the latest run
             RUN_INFO=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ env.REPO_B }}/actions/workflows/$RUN_ID/runs?branch=${{ env.BRANCH }}&per_page=1" \
               | jq -r '.workflow_runs[0]')
-
+      
             RUN_STATUS=$(echo "$RUN_INFO" | jq -r '.status')
             CONCLUSION=$(echo "$RUN_INFO" | jq -r '.conclusion')
-
+      
             echo "Current status: $RUN_STATUS"
-
+      
             if [ "$RUN_STATUS" == "completed" ]; then
               echo "Workflow completed with conclusion: $CONCLUSION"
               if [ "$CONCLUSION" == "success" ]; then
@@ -79,10 +134,10 @@ jobs:
               echo "::set-output name=result::failure"
               exit 1
             fi
-
+      
             sleep 15
           done
-
+          
       - name: Check Status and Proceed
         id: check-status-b
         if: always()
